### ISSUE TITLE
[Epiphany] The default search engine is not valid

### ISSUE THREAD

**Issue by gmikhail** [elementary/default-settings#106]
Probably a typo. "google." instead of "google.com". Because of this the out-of-box search does not work.
Locale: Russian language, Ukraine

![2019-01-03 174821](https://user-images.githubusercontent.com/4838367/50698446-a77ca200-104d-11e9-9686-66ae7477fcc7.png)

**Comment by peteruithoven** [comment]
Thanks for reporting! I'm unsure this is the right repo for this. 

It does seem like the `default-search-engine` is defined in this repo:
https://github.com/elementary/default-settings/blob/master/overrides/default-settings.gschema.override#L99

But I'm not sure that could cause your issue. What happens when you switch to English? If it doesn't occor then it's probably a translation issue.

This is the official epiphany repo: https://gitlab.gnome.org/GNOME/epiphany/

**Comment by ryonakano** [comment]
![virtualbox_elementary os_05_01_2019_12_27_39](https://user-images.githubusercontent.com/26003928/50719824-5a4c0f00-10e5-11e9-980a-3409eaf2a09e.png)

I can confirm this issue by changing the system language to Russian.

And it looks like this commit fixed this issue: https://gitlab.gnome.org/GNOME/epiphany/commit/db1b1c60d3167064c547ba9416a821ba4be641ee (So this is upstream issue)
