### ISSUE TITLE
Epiphany's default settings should be pro-privacy

### ISSUE THREAD

**Issue by uncertainquark** [elementary/default-settings#113]
Forgive me for filing this bug here as I couldn't find any repo for the slightly-modified Epiphany being shipped by elementary.

For a pro-privacy operating system like elementary, the default browser that it ships leaves a lot to be desired in terms of privacy. I think these ever-popular settings should be toggled on by default much like other pro-privacy browsers, the likes of Firefox, Safari and Brave.

1. Block ads and trackers - #111 
2. Only accept first-party cookies - #112 
3. Block popup windows - #110 

With Juno 5.1 release coming soon, it'd be great to have these tucked in the new iso for a great default, private experience for everyone.

**Comment by peteruithoven** [comment]
Thanks for the report. This isn't the right repo though, please see: https://gitlab.gnome.org/GNOME/epiphany/blob/master/CONTRIBUTING.md

In a future release of the About plug there will be an option for Epiphany ([see PR](https://github.com/elementary/switchboard-plug-about/pull/86)) linking to: 

Since we can't move issues to gitlab I'm closing this issue.

**Comment by cassidyjames** [comment]
@peteruithoven since this issue is about default settings of Epiphany in elementary OS, it does belong here. We change certain settings downstream in our OS.

However, considering it's just a meta-issue that is repeating other issues, it will remain closed. @uncertainquark, please do not file issues and then file duplicate/meta-issue issues as it just causes extra noise and time to triage. We use projects to track related issues, and we already have an org-wide Privacy project.
