### ISSUE TITLE
Sort indicator should show current state

### ISSUE THREAD

**Issue by marbetschar** [elementary/default-settings#177]
## Prerequisites
- [x] I have searched open and closed issues for duplicates.

## Describe the bug

The arrow which indicates the sort direction of a column in files should indicate the current sort direction, instead of what will happen on click. I tried to get used to this behaviour over the last couple of months, but it still confuses me:

If we sort by modified date, the behaviour of the sort indicator arrow right now is: 

-▼: ORDER BY date_modified ASC
-▲: ORDER BY date_modified DESC

Instead, I always seem to expect the opposite:

-▲: ORDER BY date_modified ASC
-▼: ORDER BY date_modified DESC

Here's the screenshot, showing the current, unexpected behaviour:

![Screenshot from 2020-05-21 11-48-15](https://user-images.githubusercontent.com/392542/82547014-52b1cc80-9b59-11ea-837f-da627d1bc15c.png)

**Sidenote:** IMHO the arrow behaviour should also be inverted for any other column, because ORDER BY file_name ASC for me is equal A-Z, but the actual sorting done in Files is Z-A:

![Screenshot from 2020-05-21 11-58-03](https://user-images.githubusercontent.com/392542/82547745-817c7280-9b5a-11ea-9f63-dd92b328d878.png)

**Comment by cassidyjames** [comment]
So, I think the way GTK is showing this is actually… correct, though I can see the confusion. The time one is the sort of confusing one, but in each case the arrow is pointing in the direction of the data flow. So if you are sorting by name (i.e. alphabetically), you see: `Filename ▼`, and then:

- `Afile.ext`
- `Bfile.ext`
- `Cfile.ext`

The flow goes top to bottom, so the arrow is pointing from top to bottom. If you reverse the direction so it alphabetical from bottom to top, the arrow is reversed: `Filename ▲` and you get:

- `Cfile.ext`
- `Bfile.ext`
- `Afile.ext`

This seems correct to me. It gets more confusing with time, as it depends on if you're thinking in terms of "timestamp" (older is smaller), or "age" (older is larger). However, the current behavior seems consistent if you think in terms of timestamp. By default, sorting ascending you get: `Modified ▼` and:

- `Yesterday at 11:00 PM`
- `Today at 10:00 AM`
- `Today at 3:00 PM`

This is showing the ascending order from top to bottom, so the arrow is pointing from top to bottom. Likewise, the reverse is: `Modified ▲` and:

- `Today at 3:00 PM`
- `Today at 10:00 AM`
- `Yesterday at 11:00 PM`

This is showing the modified time in descending order (or from bottom to top), so the arrow is pointing from bottom to top.

Correct me if I'm wrong, but is some of the confusion around the difference between "age" and "time", and/or around the shape of the arrow, where `▼` is being interpreted as "large at top and small at bottom" instead of "ascending", and vice-versa for `▲`?

**Comment by cassidyjames** [comment]
Since there's a local workaround _and_ this would require diverging from GNOME and GTK for us to address, I'm closing it. :smile: I think any further pursuit of getting this swapped should be done upstream with GTK if you feel strongly about it.

**Comment by cassidyjames** [comment]
It seems they actually reversed this upstream. I've filed an issue to use a more semantic icon name that would allow us to do something more explicit: https://gitlab.gnome.org/GNOME/gtk/-/issues/3577
