### ISSUE TITLE
Move touchegg conf here

### ISSUE THREAD

**Issue by danrabbit** [elementary/default-settings#196]
At the moment we're shipping touchegg conf in os-patches, but really it should be here. I don't think there's a good reason for it to be a patch

**Comment by JoseExposito** [comment]
I updated https://github.com/elementary/default-settings/pull/198 to be consistent with the default settings used by Gala https://github.com/elementary/gala/pull/976/files#diff-02a771e360b1bd424efabecf0240174f805908067847764e81c5e6e6f81e2910

At the moment:
- 4 fingers up: Multitasking view
- 4 fingers left/right: Switch workspaces
- 3 fingers up: Maximize or restore window
- 3 fingers left/right: Tile window

Let's see if @cassidyjames likes this defaults, I know he suggested something else.... But that was when we didn't have a UI to configure this.

Let me know if you prefer to keep patching Touchégg so I can replicate this changes in `os-patches`.

I believe this is the last piece we were missing to ship global gestures, right? Am I missing something else or do you have plans to support other global gestures? Like, I don't know, 4 fingers pinch to sow the apps menu or something.

**Comment by cassidyjames** [comment]
Ah yeah I think we wanted just to focus on workspaces by default, with 3-finger gestures (and ideally if 4-finger gestures are not configured, they would also work for these; I forget where we landed on that):

• Swipe up/down for Multitasking View
• Swipe left/right for switching workspaces

I don't think we plan to do anything with pinching by default, because that's both more finicky in general and seems to be less consistently triggerable in LibInput. Plus I think it's easy to fall down the macOS hole of having a million different gestures and not being able to discover/remember them all. 😅

**Comment by JoseExposito** [comment]
So, this by default, right?

![defaults](https://user-images.githubusercontent.com/1335948/101065902-0595c500-3596-11eb-8325-5a2a075ab9e6.png)

I'll update both Gala and this config to actually have no config at all heheheh
