### ISSUE TITLE
Option to increase sound in settings more

### ISSUE THREAD

**Issue by 4turtlez** [elementary/default-settings#241]
There are many videos that are to quiet even at full volume. It would be awesome if there was an option in audio setting to overamplify to 150%.

**Comment by cassidyjames** [comment]
Issue templates are provided for a reason; ignoring them makes it harder to triage and ultimately address issues. In the future, please use the issue template, putting the relevant information in the relevant sections.

This issue is a duplicate of https://github.com/elementary/switchboard-plug-sound/issues/68
