### ISSUE TITLE
Use duckduckgo for default search engine on Epiphany

### ISSUE THREAD

**Issue by arshubham** [elementary/default-settings#27]
Since the elementary is against tracking in the Operating System itself, this should be an acceptable change. Even though I use Epiphany just to download Firefox Nightly, I don't want google tracking me even for a bit.  😄

**Comment by codygarver** [comment]
In the past we used DDG as default search engine for Luna but design team, @cassidyjames and @danrabbit, insist that Google be default now.

**Comment by danrabbit** [comment]
I think we changed it because users were complaining and the results were bad. We could probably re-evaluate?

Re-opening just as a reminder to look into it again

**Comment by jwinnie** [comment]
@danrabbit DuckDuckGo has really improved a lot. I use it daily and, although Google still has better results, DuckDuckGo is quite usable. I think elementary should go with DuckDuckGo in Juno.

**Comment by SixFingeredAmish** [comment]
I think the best option would be to prompt users to select their preferred search engine upon starting the browser for the first time.

**Comment by cassidyjames** [comment]
I've tried reverting to DuckDuckGo for my searches, and have not gotten used to it. I'll continue to try this and see if I can, but I'm still not feeling it as a default; we've heard from too many users who expect to see and use Google and its results.

Something I've been thinking about is making the existing opt-in privacy measures more pervasive through the OS; for example, turning History off in System Settings could also switch Epiphany to an Incognito/Private Browsing mode by default (https://github.com/elementary/switchboard-plug-security-privacy/issues/52). In addition, Epiphany in Incognito could use DuckDuckGo by default to encourage further privacy ([gitlab.gnome.org/GNOME/epiphany#506](https://gitlab.gnome.org/GNOME/epiphany/issues/506)).

I think with these additions, it would make it far easier and clear how to opt into a more privacy-focused mode without spamming every user with a search engine choice that they may not understand, or that the vast majority of people will choose a single option (Google).

**Comment by mcatanzaro** [comment]
It doesn't make much sense to tie remote privacy (search engine) in with local privacy (incognito mode), though. They're two different use-cases:

 * Do you want to avoid fingerprinting and having your preferences sold to advertising companies? Then use DuckDuckGo instead of Google.
 * Do you want people with access to your user account on your computer to not see your browsing history? Then use incognito mode.

I guess most users generally want history saved locally, because it would be annoying to not be able to easily find previously-visited websites by searching in the address bar. That's why incognito mode is not enabled by default. You probably want local history even if you care about web privacy. I also assume that if you care enough about privacy to want DuckDuckGo instead of Google, you probably want it for regular browsing, not just private browsing. So that's why the upstream defaults are the way they are.

FWIW: DuckDuckGo has been the default search engine in Epiphany since 2013. My personal experience is that DuckDuckGo search results were not very good at first, but became much better somewhere back in 2015 or thereabouts; before that, I used to switch to Google whenever I didn't find the results I was looking for with DuckDuckGo, but I almost never do that nowadays.

FWIW #2: there is currently some controversy in https://gitlab.gnome.org/GNOME/epiphany/issues/616 so if that goes badly enough, we might switch away anyway.

**Comment by LilyCathelineau** [comment]
Hello! I want to point out that there isn't any proof that DuckDuckGo is private, they say they are but they do collect search data[1], despite saying it isn't personalized, they haven't actually provided evidence to prove that claim. 

By using their search engine, an address called "improving.duckduckgo.com" is pinged, without user consent, and stores user information.[2] 

DuckDuckGo, also uses the Canvas API to fingerprint users.[3]
 
It is truly awful that a lot of people in the tech community give DuckDuckGo a free pass on unsubstantiated claims of privacy. Despite all of their boasting about being private, their practices prove otherwise. There are plenty of other privacy focused search engines, without any of these search engines. 

1. "We also save searches, but again, not in a personally identifiable way, as we do not store IP addresses or unique User agent strings. We use aggregate, non-personal search data to improve things like misspellings." [DuckDuckGo Privacy Policy](https://duckduckgo.com/privacy)
2. "saves your searches, as well as which result you clicked on by requests to improving.duckduckgo.com. While there may not be an IP address or any other identifiable information associated with the saved requests, sometimes my queries themselves contain personally identifiable information." [Disable improving.duckduckgo.com requests and saving of searches](https://www.reddit.com/r/duckduckgo/comments/ab798m/disable_improvingduckduckgocom_requests_and/)
3. "DuckDuckGo is using the Canvas DOMRect API on their search engine. Canvas is used to make unique geometry measurements on target browsers, and DOMRect API uses rectangles. This can be verified with the CanvasBlocker Firefox add-on by Korbinian Kapsner." [DuckDuckGo now fingerprinting visitors](https://forums.whonix.org/t/duckduckgo-now-fingerprinting-visitors/6497)

**Comment by mcatanzaro** [comment]
> Hello! I want to point out that there isn't any proof that DuckDuckGo is private, they say they are but they do collect search data[1], despite saying it isn't personalized, they haven't actually provided evidence to prove that claim.

Well it's impossible to prove, right? That's the nature of using a third-party service. DuckDuckGo doesn't claim it doesn't save searches, just that it aggregates them and doesn't tie them to users personally. Seems fine to me, and I have no reason to disbelieve those claims. I'm not aware of other privacy-focused search engines that are nearly as popular, widely-trusted, and well-designed (looks good). To be default in Epiphany, a search engine would have to satisfy all of the above.

We'd also need a good reason to abandon our current partnership agreement with DuckDuckGo. It's not worth very much, but it's been Epiphany's default search engine since 2012-2013 or thereabouts and I'd need to see a strong reason to consider changing it. At least I'm personally quite happy with the service and its search results.

> DuckDuckGo, also uses the Canvas API to fingerprint users.[3]

If that's ever proved, then we would for sure switch to something else. [We've received assurances to the contrary from our contact at DuckDuckGo](https://gitlab.gnome.org/GNOME/epiphany/issues/616#note_406367), but at the end of the day, as with any third-party service, it's hard to prove that fingerprinting is not happening. Consider that DuckDuckGo's business would be destroyed if it was proved to be fingerprinting, though, and it seems unlikely.

**Comment by cassidyjames** [comment]
@mcatanzaro for what it's worth, I've been investigating and very pleased with the results, design, ethos, and interactions with Startpage.com.

**Comment by mcatanzaro** [comment]
> @mcatanzaro for what it's worth, I've been investigating and very pleased with the results, design, ethos, and interactions with Startpage.com.

Looks like it's had a significant redesign since the last time I tried it!

**Comment by cassidyjames** [comment]
fixed by #142
