### ISSUE TITLE
Disable middle-click paste behavior?

### ISSUE THREAD

**Issue by peteruithoven** [elementary/default-settings#5]
By default the middle mouse click pastes selected content. (This is inherited by Gnome?)

Seeing that Elementary OS calls itself a "A fast and open replacement for Windows and macOS" and this is uncommon on those platforms, shouldn't this be disabled by default? 

I remember myself being quite confused, especially when using a touchpad, where one might not suspect there is a middle mouse at all. 

I've now disabled the behavior using Gnome's Tweak tool. 

I'm hoping this is the correct repo to post this in, otherwise please let me know. I also couldn't find earlier discussions on this.

**Comment by cassidyjames** [comment]
For every person who wants to disable middle-click paste, there's one or more who depend on it for their workflow. :wink: 

I believe this is actually inherited from X itself, and is present on every Linux-based desktop OS I've seen. It's even being re-implemented in Wayland to keep that workflow.

I would be open to disabling it out of the box and seeing the response, but we've had very few complaints about the behavior and suspect we'd have a lot more complaints about the changed behavior.

**Comment by codygarver** [comment]
Thanks for the tip, I didn't realize this annoying behavior could be disabled. Happy to see it go.

**Comment by peteruithoven** [comment]
@codygarver why close the issue? 

@cassidyjames I totally get the dilemma, but I think it's a valid discussion that needs to happen.

**Comment by codygarver** [comment]
@peteruithoven because I changed the setting in this git repo.

**Comment by lewisgoddard** [comment]
Fixed in 1bfd4fc185143385d8277ac40b12071e5a2143b9

**Comment by AlonsoEnrique** [comment]
This feature is very useful, do not disable it

**Comment by uncertainquark** [comment]
I like and expect this feature in every Linux OS and it works well without any regressions for me. Please do not disable it.

**Comment by btkostner** [comment]
This setting will have a switch to re-enable it if you would like.

See: https://github.com/elementary/switchboard-plug-mouse-touchpad/pull/24

**Comment by drmyothiha** [comment]
go to /usr/share/X11/xorg.conf.d/70-synaptics.conf
search for 

Section "InputClass"
        Identifier "touchpad catchall"

and Add the following line

Option "TapButton3" "0"

work well form me

**Comment by drmyothiha** [comment]
Original answer is https://elementaryos.stackexchange.com/questions/13369/disable-three-tap-paste-gesture

**Comment by soulawaker** [comment]
@drmyothiha It worked on normal boot. In my case, when unlock screen or wake from suspend "TapButton3" always restored "2". Do you know how to prevent it? I ask it on https://elementaryos.stackexchange.com/questions/17084/how-to-prevent-restoring-synaptics-driver-setting-when-unlock-screen-or-wake-fro

**Comment by LucesEnBabel** [comment]
My system has middle click pasting disables but it would still paste on middle click.

Am I doing something wrong?

Is there a way to completely remove this feature?

**Comment by taciturasa** [comment]
There are legitimate concerns with having this behaviour in place. 

In many applications (particularly Electron based ones) that have mapped middle mouse button to pan, I.E. Figma-Linux or Gravit Designer, means that every time you go to pan your canvas, you end up pasting whatever's in your clipboard. 

I have also had issues in some applications with text input where i go to drag to scroll, but it simply pastes content in the text field instead. An example would be vscode.

I'm sure there are other applications that run into a conflict like this, but these are the ones I have had the most serious issues with. In order to be able to really use these applications, I have needed to install GNOME Tweaks to turn it off.

I understand having legacy features because they're known and people are accustomed to it, but it is my personal opinion that at the end, for a default, the default should be the one that does not seriously interfere with certain common behaviors, even if its not the convention.

**Comment by cassidyjames** [comment]
@taciturasa we don't typically cater to non-native apps in elementary OS, but even so, you do **not** need to install any third-party apps to manage this behavior; it's been available in the Mouse & Touchpad settings in elementary OS for a couple of years, now—and it's off by default. If you have enabled this feature but non-native apps you're using conflict with it, you're welcome to disable it there.

**Comment by pyrsmk** [comment]
@cassidyjames Your answer is not accurate because the behavior is still on in some applications, even if it is off in the settings. Currently, the only way I found to completely disable middle click with a touchpad (with 3 fingers) is with the answer in this post: https://unix.stackexchange.com/questions/24330/how-can-i-turn-off-middle-mouse-button-paste-functionality-in-all-programs
