### ISSUE TITLE
Solve screen real-estate issue

### ISSUE THREAD

**Issue by xfbs** [elementary/default-settings#59]
Is it possible to incorporate some changes to elementaryOS to maximize screen real estate?

#### Background

My ThinkPad X230 has a very nice, crisp (at least for 2012 standards.. heh) display, but with a resolution of only 1366x786. The issue is that by default, the menu bar and the programs' header take up 'a lot' of screen real estate, as you can see in this screenshot:

![screenshot from 2018-04-26 18-17-20](https://user-images.githubusercontent.com/786420/39318394-4c050ec6-497e-11e8-9862-94eb59e6ad0a.png)

#### Prior Art

On many operating systems, it's possible to set the menu bar (or the task bar, in the case of Windows) to auto-hide, such that it only takes up screen real estate when being used. Another option is to allow it to be resized, if that doesn't make things look awkward.

Another option, which in case probably doesn't have much to do with elementaryOS, is moving to *borderless* windows, which try to pack some functionality in the window frame (such as the top title bar) to maximize screen real estate. This is already being done by some of the high-quality elementary apps, such as the default mail app.

![screenshot from 2018-04-26 18-31-54](https://user-images.githubusercontent.com/786420/39319049-2e3342f8-4980-11e8-9fef-d7783a925fc9.png)

#### Pledge

If there is some improvement made to maximize screen real estate, I will donate at least $10 to the project, and I hope others that have an interest in this will join me.

**Comment by danrabbit** [comment]
Thanks for your report! I’m going to close it for `default-settings` because the things you described can’t be changed within the scope of this repository.

You can follow along with the discussion about an autohide for wingpanel here: https://github.com/elementary/wingpanel/issues/53

Unfortunately elementary has no ability to change the design of Mozilla Firefox, so I would suggest either using the default browser or filing an issue with Mozilla on their bug tracker
